version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: restaurant_reservation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: restaurant_reservation
    command: npm run start:dev

volumes:
  postgres_data:
